openapi: 3.0.0
info:
  title: Pia AI API
  version: 1.0.0
  description: API for managing phone numbers with Pia AI

servers:
  - url: https://api.piaai.com

paths:
  /phone_numbers/{id}:
    delete:
      summary: Delete Phone Number
      description: Deletes an existing phone number.
      tags:
        - Phone Numbers
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Unique identifier of the phone number to be deleted
      responses:
        '200':
          description: Successful deletion of phone number
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message confirming the deletion
                required:
                  - message

components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'

tags:
  - name: Phone Numbers
    description: Operations related to phone number management