openapi: 3.0.0
info:
  title: Pia AI API
  version: 1.0.0
  description: API for retrieving AI agent details

servers:
  - url: https://api.piaai.com

paths:
  /ai_agents/{agent_id}:
    get:
      summary: Get AI Agent
      description: Retrieve details of a specific AI agent
      tags:
        - AI Agents
      security:
        - BearerAuth: []
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the AI agent
      responses:
        '200':
          description: AI agent details successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AIAgent'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: AI agent not found
          content:
            application/json:
              schema:
                $ref: '../common-openapi.yaml#/components/schemas/ErrorResponse'


components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'

  schemas:
    AIAgent:
      $ref: 'ai-agent-common-openapi.yaml#/components/schemas/AIAgent'

  responses:
    UnauthorizedError:
      $ref: '../common-openapi.yaml#/components/responses/UnauthorizedError'

tags:
  - name: AI Agents
    description: Operations related to AI agent management
