openapi: 3.0.0
info:
  title: Pia AI Common AI Agent Specifications
  version: 1.0.0
  description: Common OpenAPI components shared across AI agent-related endpoints

components:
  schemas:
    AIAgent:
      type: object
      properties:
        agent_id:
          type: string
          description: Unique identifier for the AI agent
        llm_id:
          type: string
          description: A unique identifier for the Language Model (LLM) used by this AI agent
        agent_name:
          type: string
          description: Name of the AI agent
        tts:
          $ref: '#/components/schemas/TTSConfig'
        stt:
          $ref: '#/components/schemas/STTConfig'
        responsiveness:
          type: number
          minimum: 0
          maximum: 1
          description: Responsiveness of the agent (0 to 1)
        interruption_sensitivity:
          type: number
          minimum: 0
          maximum: 1
          description: Sensitivity to interruptions (0 to 1)
        use_backchanneling:
          type: boolean
          description: Whether to enable backchannel responses
        backchanneling_probability:
          type: number
          minimum: 0
          maximum: 1
          description: Frequency of backchannel responses (0 to 1)
        backchannel_words:
          type: array
          items:
            type: string
          description: List of words to use for backchannel responses
        number_of_times_to_check_human_is_listening:
          type: integer
          description: Number of times to check if the human is listening
        check_human_is_listening_phrases:
          type: array
          items:
            type: string
          description: Phrases used to check if the human is listening
        idle_time_threshold_ms:
          type: integer
          description: Idle time threshold in milliseconds
        ambient_sound:
          type: string
          description: Background ambient sound to use
        ambient_sound_volume:
          type: number
          minimum: 0
          maximum: 2
          description: Volume of the ambient sound (0 to 2)
        webhook_url:
          type: string
          description: URL for webhook notifications
        boosted_keywords:
          type: array
          items:
            type: string
          description: List of boosted keywords for speech recognition
        pronunciation_dictionary:
          type: array
          items:
            $ref: '#/components/schemas/PronunciationDictionaryItem'
          description: List of pronunciation dictionary items
        end_call_after_silence_ms:
          type: integer
          description: Duration of silence before ending call, in milliseconds
        max_call_duration_ms:
          type: integer
          description: Maximum allowed call duration in milliseconds
        initial_message:
          type: string
          description: Initial message to be played when the call starts
        voicemail_detection_timeout_ms:
          type: integer
          description: Timeout for voicemail detection in milliseconds
        post_call_analysis_data:
          type: array
          items:
            $ref: '#/components/schemas/PostCallAnalysisItem'
          description: Post call analysis data to extract from the call
        last_modification_timestamp:
          type: integer
          description: Last modification timestamp in milliseconds since epoch

    TTSConfig:
      oneOf:
        - $ref: '#/components/schemas/ElevenLabsTTSConfig'
        - $ref: '#/components/schemas/OpenAITTSConfig'
        - $ref: '#/components/schemas/GoogleTTSConfig'
        - $ref: '#/components/schemas/AzureTTSConfig'
        - $ref: '#/components/schemas/DeepgramTTSConfig'
        - $ref: '#/components/schemas/CartesiaTTSConfig'
      discriminator:
        propertyName: provider
        mapping:
          elevenlabs: '#/components/schemas/ElevenLabsTTSConfig'
          openai: '#/components/schemas/OpenAITTSConfig'
          google: '#/components/schemas/GoogleTTSConfig'
          azure: '#/components/schemas/AzureTTSConfig'
          deepgram: '#/components/schemas/DeepgramTTSConfig'
          cartesia: '#/components/schemas/CartesiaTTSConfig'

    STTConfig:
      oneOf:
        - $ref: '#/components/schemas/DeepgramSTTConfig'
        - $ref: '#/components/schemas/GoogleSTTConfig'
        - $ref: '#/components/schemas/PiaSTTConfig'
      discriminator:
        propertyName: provider
        mapping:
          deepgram: '#/components/schemas/DeepgramSTTConfig'
          google: '#/components/schemas/GoogleSTTConfig'
          pia: '#/components/schemas/PiaSTTConfig'

    # Include all TTS and STT config schemas here

    PronunciationDictionaryItem:
      type: object
      required:
        - word
        - alphabet
        - phoneme
      properties:
        word:
          type: string
          description: The word or phrase to be annotated with pronunciation.
        alphabet:
          type: string
          enum: [ipa, cmu]
          description: The phonetic alphabet used for pronunciation.
        phoneme:
          type: string
          description: Pronunciation of the word in IPA or CMU format.

    PostCallAnalysisItem:
      oneOf:
        - $ref: '#/components/schemas/StringAnalysisItem'
        - $ref: '#/components/schemas/EnumAnalysisItem'
        - $ref: '#/components/schemas/BooleanAnalysisItem'
        - $ref: '#/components/schemas/NumberAnalysisItem'

    StringAnalysisItem:
      type: object
      required:
        - type
        - name
        - description
      properties:
        type:
          type: string
          enum: [string]
        name:
          type: string
        description:
          type: string
        examples:
          type: array
          items:
            type: string

    EnumAnalysisItem:
      type: object
      required:
        - type
        - name
        - description
        - choices
      properties:
        type:
          type: string
          enum: [enum]
        name:
          type: string
        description:
          type: string
        choices:
          type: array
          items:
            type: string

    BooleanAnalysisItem:
      type: object
      required:
        - type
        - name
        - description
      properties:
        type:
          type: string
          enum: [boolean]
        name:
          type: string
        description:
          type: string

    NumberAnalysisItem:
      type: object
      required:
        - type
        - name
        - description
      properties:
        type:
          type: string
          enum: [number]
        name:
          type: string
        description:
          type: string
