openapi: 3.0.0
info:
  title: Pia AI API
  version: 1.0.0
  description: API for creating AI agents

servers:
  - url: https://api.piaai.com

paths:
  /ai_agents:
    post:
      summary: Create AI Agent
      description: Create a new AI agent with specified configurations
      tags:
        - AI Agents
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAIAgentRequest'
      responses:
        '201':
          description: AI agent successfully created
          content:
            application/json:
              schema:
                $ref: 'ai-agent-common-openapi.yaml#/components/schemas/AIAgent'
        '401':
          $ref: '../common-openapi.yaml#/components/responses/UnauthorizedError'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'

  schemas:
    CreateAIAgentRequest:
      type: object
      required:
        - llm_id
        - stt
        - tts
      properties:
        llm_id:
          type: string
          description: A unique identifier for the Language Model (LLM) to be used by this AI agent.
        agent_name:
          type: string
          nullable: true
          description: A custom name for your AI agent.
        tts:
          $ref: 'ai-agent-common-openapi.yaml#/components/schemas/TTSConfig'
        stt:
          $ref: 'ai-agent-common-openapi.yaml#/components/schemas/STTConfig'
        responsiveness:
          type: number
          minimum: 0
          maximum: 1
          description: Responsiveness of the agent (0 to 1)
        interruption_sensitivity:
          type: number
          minimum: 0
          maximum: 1
          description: Sensitivity to interruptions (0 to 1)
        use_backchanneling:
          type: boolean
          description: Whether to enable backchannel responses
        backchanneling_probability:
          type: number
          minimum: 0
          maximum: 1
          description: Frequency of backchannel responses (0 to 1)
        backchannel_words:
          type: array
          items:
            type: string
          description: List of words to use for backchannel responses
        number_of_times_to_check_human_is_listening:
          type: integer
          description: Number of times to check if the human is listening
        check_human_is_listening_phrases:
          type: array
          items:
            type: string
          description: Phrases used to check if the human is listening
        idle_time_threshold_ms:
          type: integer
          description: Idle time threshold in milliseconds
        ambient_sound:
          type: string
          description: Background ambient sound to use
        ambient_sound_volume:
          type: number
          minimum: 0
          maximum: 2
          description: Volume of the ambient sound (0 to 2)
        webhook_url:
          type: string
          description: URL for webhook notifications
        boosted_keywords:
          type: array
          items:
            type: string
          description: List of boosted keywords for speech recognition
        pronunciation_dictionary:
          type: array
          items:
            $ref: 'ai-agent-common-openapi.yaml#/components/schemas/PronunciationDictionaryItem'
          description: List of pronunciation dictionary items
        end_call_after_silence_ms:
          type: integer
          description: Duration of silence before ending call, in milliseconds
        max_call_duration_ms:
          type: integer
          description: Maximum allowed call duration in milliseconds
        initial_message:
          type: string
          description: Initial message to be played when the call starts
        voicemail_detection_timeout_ms:
          type: integer
          description: Timeout for voicemail detection in milliseconds
        post_call_analysis_data:
          type: array
          items:
            $ref: 'ai-agent-common-openapi.yaml#/components/schemas/PostCallAnalysisItem'
          description: Post call analysis data to extract from the call

tags:
  - name: AI Agents
    description: Operations related to AI agent management