openapi: 3.0.0
info:
  title: Pia AI API
  version: 1.0.0
  description: API for deleting AI agents

servers:
  - url: https://api.piaai.com

paths:
  /ai_agents/{agent_id}:
    delete:
      summary: Delete AI Agent
      description: Delete a specific AI agent
      tags:
        - AI Agents
      security:
        - BearerAuth: []
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
          description: Unique identifier of the AI agent to delete
      responses:
        '204':
          description: AI agent successfully deleted
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          description: AI agent not found
          content:
            application/json:
              schema:
                $ref: '../common-openapi.yaml#/components/schemas/ErrorResponse'


components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'

  responses:
    UnauthorizedError:
      $ref: '../common-openapi.yaml#/components/responses/UnauthorizedError'

tags:
  - name: AI Agents
    description: Operations related to AI agent management
