openapi: 3.0.0
info:
  title: Pia AI API - Call Analysis
  version: 2.0.0
  description: API for accessing call analysis information

paths:
  /calls/{call_id}/analysis:
    get:
      summary: Retrieve Call Analysis
      description: Retrieve detailed analysis information about a specific call.
      tags:
        - Call Analysis
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: call_id
          required: true
          schema:
            type: string
          description: ID of the call to access analysis information for.
      responses:
        '200':
          description: Successful call analysis data retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './post-call-analysis-common-openapi.yaml#/components/schemas/PostCallAnalysisResult'
        '401':
          $ref: '../../common-openapi.yaml#/components/responses/UnauthorizedError'
        '404':
          description: Call not found
          content:
            application/json:
              schema:
                $ref: '../../common-openapi.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../../common-openapi.yaml#/components/securitySchemes/BearerAuth'

tags:
  - name: Call Analysis
    description: Operations related to call analysis
