openapi: 3.0.0
info:
  title: Pia AI API - Delete Call Analysis
  version: 2.0.0
  description: API for deleting call analysis items

paths:
  /ai_agents/{agent_id}/analysis:
    delete:
      summary: Delete Call Analysis
      description: Delete existing analysis items for a specific AI agent.
      tags:
        - Call Analysis
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: agent_id
          required: true
          schema:
            type: string
          description: ID of the AI agent to delete analysis items for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
                description: IDs of the analysis items to be deleted
      responses:
        '200':
          description: Successfully deleted call analysis items
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: A success message confirming the deletion of analysis items
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '../../common-openapi.yaml#/components/schemas/ErrorResponse'
        '401':
          $ref: '../../common-openapi.yaml#/components/responses/UnauthorizedError'
        '404':
          description: AI agent not found or analysis items not found
          content:
            application/json:
              schema:
                $ref: '../../common-openapi.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../../common-openapi.yaml#/components/securitySchemes/BearerAuth'

tags:
  - name: Call Analysis
    description: Operations related to call analysis
