openapi: 3.0.0
info:
  title: Pia AI API - LLM Management
  version: 1.0.0
  description: API for deleting PIA LLMs

servers:
  - url: https://api.piaai.com

paths:
  /llms/{llm_id}:
    delete:
      summary: Delete LLM
      description: Delete a specific PIA LLM by its ID
      tags:
        - LLMs
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: llm_id
          required: true
          schema:
            type: string
            format: uuid
          description: The unique identifier of the LLM to delete
      responses:
        '204':
          description: Successfully deleted LLM
        '404':
          description: LLM not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'

  schemas:
    ErrorResponse:
      $ref: '../common-openapi.yaml#/components/schemas/ErrorResponse'

tags:
  - name: LLMs
    description: Operations related to PIA LLM management
