openapi: 3.0.0
info:
  title: Pia AI API
  version: 2.0.0
  description: API for initiating and managing web-based calls with Pia AI

servers:
  - url: https://api.piaai.com

paths:
  /create-web-call:
    post:
      summary: Create a new web call
      description: Initiate a new web-based call session with optional parameters for customization.
      tags:
        - Calls
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'calls-common-openapi.yaml#/components/schemas/CreateWebCallRequest'
      responses:
        '201':
          description: Call successfully initiated
          content:
            application/json:
              schema:
                $ref: 'calls-common-openapi.yaml#/components/schemas/WebCallResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '../common-openapi.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'