openapi: 3.0.0
info:
  title: Pia AI API
  version: 2.0.0
  description: API for initiating outbound phone calls

servers:
  - url: https://api.piaai.com

paths:
  /create-phone-call:
    post:
      summary: Create a new phone call
      description: Initiate a new outbound call from a specified number to a target number, with optional parameters for customization.
      tags:
        - Calls
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'calls-common-openapi.yaml#/components/schemas/CreatePhoneCallRequest'
      responses:
        '201':
          description: Call successfully initiated
          content:
            application/json:
              schema:
                $ref: 'calls-common-openapi.yaml#/components/schemas/PhoneCallResponse'
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                $ref: '../common-openapi.yaml#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    BearerAuth:
      $ref: '../common-openapi.yaml#/components/securitySchemes/BearerAuth'